### ISSUE TITLE
Tags in code blocks are taken

### ISSUE THREAD

**Issue by louis030195** [mfarragher/obsidiantools#24]
As a placeholder.
I think code blocks should be ignored for tags? What do you think?

<img width="910" alt="image" src="https://user-images.githubusercontent.com/25003283/207360183-60f9a594-1a0b-45d2-9c80-c643940c2b71.png">

```
 "file_tags": [
        "meta",
        "idea",
        "shower-thought",
        "to-digest",
        "shower-thought",
        "introduction",
        "shower-thought\"",
        "guru\"",
        "shroedinger-uncertain\"",
        "floating-point-error\"",
        "socratic\""
      ]
```

**Comment by mfarragher** [comment]
So far I've added this to the code: https://github.com/mfarragher/obsidiantools/commit/5b73e6f7d50a475adcd1f12023e1ba4b42626777

I have also been prototyping some code to listen to file changes with another library.  More work is needed to play around with async for the attr updates.

**Comment by mfarragher** [comment]
Do you have a short example of an MD file where hashtags are being recognised as ?

When I add this to Sussudio.md: 
```python
#code_comment_not_tag
```
The current test `test_tags_index` still passes, as desired.

But when I add this:
```python
#code_comment_not_tag
#code-comment-not-tag
```
It recognises those Python comments as two tags.  Interesting how having 2+ lines makes a difference.

**Comment by mfarragher** [comment]
Via `_get_html_from_md_file` function, the HTML was getting recognised as:
```
<p>```python</p>
<h1>#code_comment_not_tag</h1>
<h1>#code-comment-not-tag</h1>
<p>```</p>
```

Adding `superfences` extension (https://github.com/mfarragher/obsidiantools/commit/228ec4bfa6637551ea7fa4e28ff1fb82c53f740e), this is better, as everything in the `code` tag gets wiped out as expected:
```
<div class="highlight"><pre><span></span><code><span class="c1"># #code_comment_not_tag</span>
<span class="c1"># #code-comment-not-tag</span>
</code></pre></div>
```

**Comment by mfarragher** [comment]
Tests pass for this now: https://github.com/mfarragher/obsidiantools/commit/073881b94da5c7d429b9e5f926027088833d33c6

I added an `if` statement in there, like in the OP.
