### ISSUE TITLE
Handle .md inside wikilinks to reflect Obsidian graph

### ISSUE THREAD

**Issue by mfarragher** [mfarragher/obsidiantools#26]
[[Foo]] and [[Bar.md]] will both be related to note 'Foo' in the knowledge graph.

Currently, wikilinks getters will extract the wikilinks as 'Foo' and 'Bar.md'.
The expected behaviour of getters to reflect Obsidian's behaviour is 'Foo' and 'Bar' respectively.

**Comment by mfarragher** [comment]
@martinlackner The commit in `dev` branch addresses the issue you raised: https://github.com/mfarragher/obsidiantools/commit/1d04903c866d2bdd24cea43072ef7791f210a8ae
I changed one of the wikilinks in the test vault to include `.md`.

The solution requires Python 3.9.  I've incremented the minimum Python version as this will inevitably be the minimum requirement of some of the required libraries next year.

**Comment by martinlackner** [comment]
Great, thanks!
