### ISSUE TITLE
UnicodeDecodeError when connecting to Obsidian Vault

### ISSUE THREAD

**Issue by virtualarchitectures** [mfarragher/obsidiantools#6]
Hi, I'm testing out the package and I'm getting an error when I try to connect via Jupyter notebook in Windows 10: `vault = otools.Vault(vault_dir).connect().gather()`.

I'm receiving the following UnicodeDecodeError: `UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1400: character maps to <undefined>`.

Assuming the filepath and connection are working I'm unclear whether it is a problem I can correct in Obsidian or if it is a problem with the parser used by obsidiantools. Can you advise how I can resolve the issue?

![image](https://user-images.githubusercontent.com/10799911/147713588-74180f4e-90a0-4a6a-9e1a-fc826552e638.png)

For reference the stack trace is as follows:

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19592/2568229718.py in <module>
----> 1 vault = otools.Vault(vault_dir).connect().gather()
      2 print(f"Connected?: {vault.is_connected}")
      3 print(f"Gathered?:  {vault.is_gathered}")

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\api.py in connect(self)
    199         if not self._is_connected:
    200             # default graph to mirror Obsidian's link counts
--> 201             wiki_link_map = self._get_wikilinks_index()
    202             G = nx.MultiDiGraph(wiki_link_map)
    203             self._graph = G

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\api.py in _get_wikilinks_index(self)
    438         where k is the md filename
    439         and v is list of ALL wikilinks found in k"""
--> 440         return {k: get_wikilinks(self._dirpath / v)
    441                 for k, v in self._file_index.items()}
    442 

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\api.py in <dictcomp>(.0)
    438         where k is the md filename
    439         and v is list of ALL wikilinks found in k"""
--> 440         return {k: get_wikilinks(self._dirpath / v)
    441                 for k, v in self._file_index.items()}
    442 

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\md_utils.py in get_wikilinks(filepath)
     92         list of strings
     93     """
---> 94     plaintext = _get_ascii_plaintext_from_md_file(filepath, remove_code=True)
     95 
     96     wikilinks = _get_all_wikilinks_from_html_content(

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\md_utils.py in _get_ascii_plaintext_from_md_file(filepath, remove_code)
    265     """md file -> html -> ASCII plaintext"""
    266     # strip out front matter (if any):
--> 267     html = _get_html_from_md_file(filepath)
    268     if remove_code:
    269         html = _remove_code(html)

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\md_utils.py in _get_html_from_md_file(filepath)
    251 def _get_html_from_md_file(filepath):
    252     """md file -> html (without front matter)"""
--> 253     _, content = _get_md_front_matter_and_content(filepath)
    254     return markdown.markdown(content, output_format='html')
    255 

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\md_utils.py in _get_md_front_matter_and_content(filepath)
    242     with open(filepath) as f:
    243         try:
--> 244             front_matter, content = frontmatter.parse(f.read())
    245         except yaml.scanner.ScannerError:
    246             # for invalid YAML, return the whole file as content:

~\anaconda3\envs\Obsidian_Tools\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1400: character maps to <undefined>
```

**Comment by virtualarchitectures** [comment]
I looked into this further and tried running in VSCode to see if I could spot an issue. Validating the path with `os.path.exists(vault_dir)` returns `True`. I checked over my Obsidian `note.md` names for any slashes but the only non-alpha numeric characters I have are: '_', '-' and '&'. 

Out of curiosity I dropped the call to `Path` leaving `vault_dir = os.path.abspath(input('Vault directory: '))`. When run this results in a TypeError: `TypeError: unsupported operand type(s) for /: 'str' and 'str'`.

I'm expecting your code works internally using the pathlib Path objects. But just in case its useful...here's the stack trace:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19148/2568229718.py in <module>
----> 1 vault = otools.Vault(vault_dir).connect().gather()
      2 print(f"Connected?: {vault.is_connected}")
      3 print(f"Gathered?:  {vault.is_gathered}")

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\api.py in __init__(self, dirpath, include_subdirs, include_root)
     87         """
     88         self._dirpath = dirpath
---> 89         self._file_index = self._get_md_relpaths_by_name(
     90             include_subdirs=include_subdirs,
     91             include_root=include_root)

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\api.py in _get_md_relpaths_by_name(self, **kwargs)
    432             dict
    433         """
--> 434         return {f.stem: f for f in self._get_md_relpaths(**kwargs)}
    435 
    436     def _get_wikilinks_index(self):

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\api.py in _get_md_relpaths(self, **kwargs)
    422             list
    423         """
--> 424         return get_md_relpaths_matching_subdirs(self._dirpath, **kwargs)
    425 
    426     def _get_md_relpaths_by_name(self, **kwargs):

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\md_utils.py in get_md_relpaths_matching_subdirs(dir_path, include_subdirs, include_root)
     60     """
     61     if not include_subdirs and include_root:
---> 62         return get_md_relpaths_from_dir(dir_path)
     63     elif not include_subdirs and not include_root:
     64         return [i for i in get_md_relpaths_from_dir(dir_path)

~\anaconda3\envs\Obsidian_Tools\lib\site-packages\obsidiantools\md_utils.py in get_md_relpaths_from_dir(dir_path)
     27     """
     28     return [Path(p).relative_to(dir_path)
---> 29             for p in glob(str(dir_path / '**/*.md'), recursive=True)]
     30 
     31 

TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by mfarragher** [comment]
@virtualarchitectures thanks for raising this - this doesn't look like a filename issue from the error trace, it looks like this is happening when content in a file is being parsed.

Are you using non-Latin text in notes, any special characters, etc.? This is more info on the [0x9d](https://stackoverflow.com/questions/45749093/in-what-8-bit-character-set-is-0x9d-meaningful) character online.  A character that you may not be able to see clearly in one of your notes, so it may be a pain to find which file has it.

It's not ideal that the vault 'connection' fails because of (possibly) one note not being able to be read.  Would be great to see how we can make this more robust. :slightly_smiling_face:

The python frontmatter parsing uses `utf-8` as default and that's kept in the implementation of obsidiantools.  It would be difficult to get an approach that can infer the right encoding of a file.  One of your notes probably doesn't align with `utf-8`.

Initial ideas on what could be done as a 'fix', to let the vault setup complete:
- Robust but tricky: one way around this may be to introduce `chardet` as a dependency to handle files where `utf-8` doesn't work
- Quick way: if file is not `utf-8`, print an error and let other files in the vault continue processing so that the vault object can still be set.

**Comment by virtualarchitectures** [comment]
Thanks for looking into this. I've isolated it to a folder containing of notes containing iFrames for YouTube videos. I can connect to the individual files .md files in the folder but not to the to the folder itself. Doing so raises the original Unicode Error. The notes in that folder don't contain any inlinks but they do have YAML frontmatter with tags. The tags seem pretty standard though. 

I tried writing a loop to read each file with UTF-8 encoding using os.open() but was getting false 'file not found' errors. I think that was because I'm not so familiar with pathlib. If there's a loop you want me to try and run to isolate the error and get some more info I'm happy to give it a try.

**Comment by mfarragher** [comment]
Try re-installing the package to bring in changes I've done in dev branch, and see if the error persists?:
`pip install git+https://github.com/mfarragher/obsidiantools.git@dev`

The main change I've done is to specify `utf-8` encoding when a markdown file is opened.  What might be happening is that your computer uses something different, so setting it as `utf-8` explicitly might help: https://www.python.org/dev/peps/pep-0597/

**Comment by virtualarchitectures** [comment]
That was spot on. It is now reading my vault in Windows perfectly from the top level down. This is a really nice package. Great to have a bridge from Obsidian to NetworkX! Also a useful reminder for myself on explicit UTF-8 encoding. Many thanks.
